import 'language.dart';

class LanguageList{
  List<Language> languageList = [
    Language(language: "English", nationality: ""),
    Language(language: "Afrikaans", nationality: ""),
    Language(language: "Bahasa Indonesia", nationality: "Indonesian"),
    Language(language: "Bahasa Melayu", nationality: "Malay"),
    Language(language: "Dansk", nationality: "Danish"),
    Language(language: "Deutsch", nationality: "German"),
    Language(language: "English (UK)", nationality: ""),
    Language(language: "Espanol", nationality: "Spanish (Latin America)"),
    Language(language: "Espanol (Espana)", nationality: "Spanish (Spain)"),
    Language(language: "Filipino", nationality: ""),
    Language(language: "Francais (Canada)", nationality: "French (Canada)"),
    Language(language: "Francais (France)", nationality: "French (France)"),
    Language(language: "Hrvatski", nationality: "Croatian"),
    Language(language: "Italiano", nationality: "Italian"),
    Language(language: "Magyar", nationality: "Hungarian"),
    Language(language: "Nederlands", nationality: "Dutch"),
    Language(language: "Norsk (bokmal)", nationality: "Norwegian (bokmal)"),
    Language(language: "Polski", nationality: "Polish"),
    Language(language: "Portugues (Brasil)", nationality: "Portuguese (Brazil)"),
    Language(language: "Portugues (Portugal)", nationality: "Portuguese (Portugal)"),
    Language(language: "Romana", nationality: "Romanian"),
    Language(language: "Slovencina", nationality: "Slovak"),
    Language(language: "Suomi", nationality: "Finnish"),
    Language(language: "Svenska", nationality: "Swedish"),
    Language(language: "Tiếng Việt", nationality: "Vietnamese"),
    Language(language: "Türkce", nationality: "Turkish"),
    Language(language: "čeština", nationality: "Czech"),
    Language(language: "Ελληνικά", nationality: "Greek"),
    Language(language: "български", nationality: "Bulgarian"),
    Language(language: "русский", nationality: "Russian"),
    Language(language: "Українська", nationality: "Ukrainian"),
    Language(language: "Српски", nationality: "Serbian"),
    Language(language: "עִברִית", nationality: "Hebrew"),
    Language(language: "العربية", nationality: "Arabic"),
    Language(language: "فارسی", nationality: "Persian"),
    Language(language: "हिन्दी", nationality: "Hindi"),
    Language(language: "ภาษา", nationality: "Thai"),
    Language(language: "中文(简体)", nationality: "Chinese (simplified)"),
    Language(language: "中文（繁體，台灣）", nationality: "Chinese (traditional, taiwan)"),
    Language(language: "中文（繁體，香港）", nationality: "Chinese (traditional, hong kong)"),
    Language(language: "日本語", nationality: "Japanese"),
    Language(language: "한국어", nationality: "Korean"),
  ];
  List<Language> getLanguage(){
    return languageList;
  }
}