class City{
  List<String> cityNames = [
    "Banda Aceh",
    "Langsa",
    "Lhokseumawe",
    "Sabang",
    "Subulussalam",
    "Binjai",
    "Gunungsitoli",
    "Medan",
    "Padang Sidempuan",
    "Pematangsiantar",
    "Sibolga",
    "Tanjungbalai",
    "Tebing Tinggi",
    "Bukittinggi",
    "Padang",
    "Padang Panjang",
    "Pariaman",
    "Payakumbuh",
    "Sawahlunto",
    "Solok",
    "Jambi",
    "Sungai Penuh",
    "Dumai",
    "Pekanbaru",
    "Bengkulu",
    "Lubuklinggau",
    "Pagar Alam",
    "Palembang",
    "Prabumulih",
    "Bandar Lampung",
    "Metro",
    "Pangkalpinang",
    "Batam",
    "Tanjungpinang",
    "Cilegon",
    "Serang",
    "Tangerang",
    "South Tangerang",
    "Bandung",
    "Banjar",
    "Bekasi",
    "Bogor",
    "Cimahi",
    "Cirebon",
    "Depok",
    "Sukabumi",
    "Tasikmalaya",
    "Magelang",
    "Surakarta",
    "Salatiga",
    "Semarang",
    "Pekalongan",
    "Tegal",
    "Batu",
    "Blitar",
    "Kediri",
    "Madiun",
    "Malang",
    "Mojokerto",
    "Pasuruan",
    "Probolinggo",
    "Surabaya",
    "Yogyakarta",
    "Denpasar",
    "Mataram",
    "Bima",
    "Kupang",
    "Pontianak",
    "Singkawang",
    "Banjarmasin",
    "Banjarbaru",
    "Palangka Raya",
    "Balikpapan",
    "Bontang",
    "Samarinda",
    "Gorontalo",
    "Makassar",
    "Palopo",
    "Parepare",
    "Baubau",
    "Kendari",
    "Palu",
    "Bitung",
    "Kotamobagu",
    "Manado",
    "Tomohon",
    "Ambon",
    "Tual",
    "Ternate",
    "Tidore",
    "Sorong",
    "Jayapura",
  ];
}